<?php
session_start();
include_once "/../../../application/controllers/add_offer_controller.php";
include_once "/../../../application/models/offer.php";
$_SESSION["id"] = 2;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-12-23 at 00:43:30.
 */
class AddOfferControllerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var AddOfferController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new AddOfferController;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * Generated from @assert ("testName", "testDescr", "2014-12-3", "2014-12-5", 5, 3) == "1".
     *
     * @covers AddOfferController::addOffer
     */
    public function testaddOffer() {
        $this->assertEquals(
                array("1"), 
                $this->object->addOffer("testName", "testDescr", "1", "2014-12-3", "2014-12-5", "5", "3")
        );
    }

    /**
     * @covers AddOfferController::offerName
     * @todo   Implement testOfferName().
     */
    public function testOfferName() {
        $this->assertEquals(
                0,
                $this->object->offerName("testName")
        );
    }
    
    /**
     * @covers AddOfferController::offerName
     * @todo   Implement testOfferName().
     */
    public function testOfferNameInvalid() {
        $this->assertEquals(
                -1,
                $this->object->offerName("!@#$%^")
        );
    }
    
    /**
     * @covers AddOfferController::offerName
     * @todo   Implement testOfferName().
     */
    public function testOfferNameEmpty() {
        $this->assertEquals(
                -2,
                $this->object->offerName("")
        );
    }

    /**
     * @covers AddOfferController::offerDescr
     * @todo   Implement testOfferDescr().
     */
    public function testOfferDescr() {
        $this->assertEquals(
                0,
                $this->object->offerDescr("testDescr")
        );
    }
    
    /**
     * @covers AddOfferController::offerDescr
     * @todo   Implement testOfferDescr().
    */
    public function testOfferDescrInvalid() {
        $this->assertEquals(
                -3,
                $this->object->offerDescr("!#$%^&*")
        );
    }

    /**
     * @covers AddOfferController::startDate
     * @todo   Implement testStartDate().
     */
    public function testStartDate() {
        $this->assertEquals(
                0,
                $this->object->startDate("2014-12-3")
        );
    }
    
    /**
     * @covers AddOfferController::startDate
     * @todo   Implement testStartDate().
     */
    public function testStartDateEmpty() {
        $this->assertEquals(
                -4,
                $this->object->startDate("")
        );
    }

    /**
     * @covers AddOfferController::endDate
     * @todo   Implement testEndDate().
     */
    public function testEndDate() {
        $this->assertEquals(
                0,
                $this->object->endDate("2014-12-5")
        );
    }
    
    /**
     * @covers AddOfferController::endDate
     * @todo   Implement testEndDate().
     */
    public function testEndDateEmpty() {
        $this->assertEquals(
                -5,
                $this->object->endDate("")
        );
    }

    /**
     * @covers AddOfferController::discount
     * @todo   Implement testDiscount().
     */
    public function testDiscount() {
        $this->assertEquals(
                0,
                $this->object->discount("5")
        );
    }
    
    /**
     * @covers AddOfferController::discount
     * @todo   Implement testDiscount().
     */
    public function testDiscountInvalid() {
        $this->assertEquals(
                -6,
                $this->object->discount("something")
        );
    }
    
    /**
     * @covers AddOfferController::discount
     * @todo   Implement testDiscount().
     */
    public function testDiscountMoreThan100() {
        $this->assertEquals(
                "-7",
                $this->object->discount("105")
        );
    }
    
    /**
     * @covers AddOfferController::discount
     * @todo   Implement testDiscount().
     */
    public function testDiscountLessThan0() {
        $this->assertEquals(
                -6,
                $this->object->discount("-10")
        );
    }
    
    /**
     * @covers AddOfferController::discount
     * @todo   Implement testDiscount().
     */
    public function testDiscountEmpty() {
        $this->assertEquals(
                -8,
                $this->object->discount("")
        );
    }

    /**
     * @covers AddOfferController::price
     * @todo   Implement testPrice().
     */
    public function testPrice() {
        $this->assertEquals(
                0,
                $this->object->price("3")
        );
    }
    
    /**
     * @covers AddOfferController::price
     * @todo   Implement testPrice().
     */
    public function testPriceInvalid() {
        $this->assertEquals(
                -9,
                $this->object->price("something")
        );
    }
    
    /**
     * @covers AddOfferController::price
     * @todo   Implement testPrice().
     */
    public function testPriceLessThan0() {
        $this->assertEquals(
                -9,
                $this->object->price("-10")
        );
    }
    
    /**
     * @covers AddOfferController::price
     * @todo   Implement testPrice().
     */
    public function testPriceEmpty() {
        $this->assertEquals(
                -10,
                $this->object->price("")
        );
    }

}
