<?php
    include_once "../../../application/controllers/add_offer_controller.php";
    include_once "../../../application/models/offer.php";
    session_start();
    $_SESSION["id"] = 2;
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-12-23 at 00:43:30.
 */
class AddOfferControllerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var AddOfferController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new AddOfferController;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * Generated from @assert ("sdfwesfw", "wefewfewf", "2014-12-3", "2014-12-5", 5, 3) == "1".
     *
     * @covers AddOfferController::addOffer
     */
    public function testaddOffer() {
        $this->assertEquals(
                array("1")
                , $this->object->addOffer("sdfwesfw", "wefewfewf", "1", "2014-12-3", "2014-12-5", "5", "3")
        );
    }

    /**
     * @covers AddOfferController::offerName
     * @todo   Implement testOfferName().
     */
    public function testOfferName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AddOfferController::offerDescr
     * @todo   Implement testOfferDescr().
     */
    public function testOfferDescr() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AddOfferController::startDate
     * @todo   Implement testStartDate().
     */
    public function testStartDate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AddOfferController::endDate
     * @todo   Implement testEndDate().
     */
    public function testEndDate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AddOfferController::discount
     * @todo   Implement testDiscount().
     */
    public function testDiscount() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AddOfferController::price
     * @todo   Implement testPrice().
     */
    public function testPrice() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
