<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-12-19 at 18:50:01.
 */
class AddOfferControllerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var AddOfferController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new AddOfferController;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers AddOfferController::addOffer
     * @todo   Implement testAddOffer().
     */
    public function testAddOffer() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
