<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-01-12 at 19:35:52.
 */
class DeleteOfferControllerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var DeleteOfferController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new DeleteOfferController;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers DeleteOfferController::DeleteOffer
     * @todo   Implement testDeleteOffer().
     */
    public function testDeleteOffer() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
