<?php
include_once "/../../../application/controllers/delete_offer_controller.php";
/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-01-12 at 19:35:52.
 */
class DeleteOfferControllerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var DeleteOfferController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new DeleteOfferController;
        mysql_query(
                    "INSERT INTO
                        offer
                    SET
                        id = '0',
                        comp_id = '1',
                        cat_id = '1',
                        offer_name = 'T-Shirts',
                        offer_descr = '20% φθηνότερα',
                        start_date = '2014-12-01',
                        end_date = '2014-05-01',
                        discount = '20',
                        price = '15'"
            ); 
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers DeleteOfferController::DeleteOffer
     * @todo   Implement testDeleteOffer().
     */
    public function testDeleteOffer() {
        $this->assertEquals(
                "T-Shirts", 
                $this->object->DeleteOffer(0)
        );
    }
        
    /**
     * @covers DeleteOfferController::DeleteOffer
     * @todo   Implement testDeleteOffer().
     */
    public function testDeleteOfferInvaild() {
        $this->assertEquals(
                "FALSE", 
                $this->object->DeleteOffer(-5)
        );
    }
}
