<?php
include_once "/../../../application/controllers/login_controller.php";
include_once "/../../../application/models/company.php";
/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-12-24 at 17:14:19.
 */
class loginControllerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var loginController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new loginController;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers loginController::login
     * @todo   Implement testLogin().
     */
    public function testLogin() {
        // Remove the following lines when you implement this test.
        $this->assertEquals(
                -1,
                $this->object->login("carrefour", "12345")
        );
    }
    
    /**
     * @covers loginController::login
     * @todo   Implement testLogin().
     */
    public function testEmptyLogin() {
        // Remove the following lines when you implement this test.
        $this->assertEquals(
                -2,
                $this->object->login("", "")
        );
    }
    
    /**
     * @covers loginController::login
     * @todo   Implement testLogin().
     */
    public function testLoginWithOnlyUsername() {
        // Remove the following lines when you implement this test.
        $this->assertEquals(
                -2,
                $this->object->login("carrefour", "")
        );
    }
    
    /**
     * @covers loginController::login
     * @todo   Implement testLogin().
     */
    public function testLoginWithOnlyPassword() {
        // Remove the following lines when you implement this test.
        $this->assertEquals(
                -2,
                $this->object->login("", "12345")
        );
    }
    
    /**
     * @covers loginController::login
     * @todo   Implement testLogin().
     */
    public function testLoginInvalid() {
        // Remove the following lines when you implement this test.
        $this->assertEquals(
                -2,
                $this->object->login("!@#$%^", "!@#$%^")
        );
    }
    
}
