<?php

include_once "/../../../application/controllers/profile_update_controller.php";
session_start();
$_SESSION["id"] = 9;
/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-12-28 at 15:54:58.
 */
class ProfileUpdateControllerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var ProfileUpdateController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new ProfileUpdateController;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers ProfileUpdateController::profileUpdate
     */
    public function testProfileUpdateNoChanges() {
        $this->assertEquals(
                array("1"), 
                $this->object->profileUpdate("testName", "testDisplay", "testPassword", "test@test.com", "1212212112", "test", "test 13", "160 33", "39.3854631332584", "22.1632351250000")
        );
    }
    
    /**
     * @covers ProfileUpdateController::profileUpdate
     */
    public function testProfileUpdateWithChanges() {
        $this->assertEquals(
                array("1"), 
                $this->object->profileUpdate("testName123", "testDisplay123", "testPassword123", "test123@test.com", "1212212112", "test", "test 13", "160 33", "39.3854631332584", "22.1632351250000")
        );
    }
    
    /**
     * @covers ProfileUpdateController::profileUpdate
     */
    public function testProfileUpdateEmpty() {
        $this->assertEquals(
                array(-2, -4, -6, -9, -12, -14, -15, -16, -17, -18), 
                $this->object->profileUpdate("", "", "", "", "", "", "", "", "", "")
        );
    }
    
    /**
     * @covers ProfileUpdateController::profileUpdate
     */
    public function testProfileUpdateInvalidInput() {
        $this->assertEquals(
                array(-3, -5, -7, -10, -13, 0, 0, 0, 0, 0), 
                $this->object->profileUpdate("#$%#^&^%&", "#$%#^&^%&", "#$%#^&^%&", "#$%#^&^%&", "#$%#^&^%&", "test", "test 13", "160 33", "39.3854631332584", "22.1632351250000")
        );
    }
    
    /**
     * @covers ProfileUpdateController::profileUpdate
     */
    public function testProfileUpdateAlreadyExists() {
        $this->assertEquals(
                array(-1, 0, 0, -8, -11, 0, 0, 0, 0, 0), 
                $this->object->profileUpdate("carrefour", "testDisplay", "testPassword", "carrefour_serres@gmail.com", "2321056230", "test", "test 13", "160 33", "39.3854631332584", "22.1632351250000")
        );
    }
    
    /**
     * @covers ProfileUpdateController::compName
     */
    public function testCompName() {
        $this->assertEquals(
                0, 
                $this->object->CompName("testName")
        );
    }
    
    public function testCompNameExists() {
        $this->assertEquals(
                -1,
                $this->object->compName("carrefour")
        );
    }
    

    public function testCompNameEmpty() {
        $this->assertEquals(
                -2,
                $this->object->compName("")
        );
    }
    
    public function testCompNameInvalid(){
        $this->assertEquals(
                -3,
                $this->object->compName("@#$%^")
        );
    }
    
    /**
     * @covers ProfileUpdateController::displayName
     */
    public function testDisplayName() {
        $this->assertEquals(
                0, 
                $this->object->DisplayName("testName")
        );
    }
    
    public function testDisplayNameEmpty(){
        $this->assertEquals(
                -4,
                $this->object->displayName("")
        );
    }
    
    public function testDisplayNameInvalid(){
        $this->assertEquals(
                -5,
                $this->object->displayName("@#$%^")
        );
    }

    /**
     * @covers ProfileUpdateController::password
     */
    public function testPassword() {
        $this->assertEquals(
                0, 
                $this->object->password("123456789")
        );
    }
    
    public function testPasswordEmpty() {
        $this->assertEquals(
                -6, 
                $this->object->password("")
        );
    }
    
    public function testPasswordInvalid(){
        $this->assertEquals(
                -7,
                $this->object->password("@#$%^&")
        );
    }

    /**
     * @covers ProfileUpdateController::email
     */
    public function testEmail() {
        $this->assertEquals(
                0, 
                $this->object->email("testEmail@gmail.com")
        );
    }
    
    public function testEmailExists() {
        $this->assertEquals(
                -8,
                $this->object->email("carrefour_serres@gmail.com")
        );
    }
    
    public function testEmailEmpty() {
        $this->assertEquals(
                -9, 
                $this->object->email("")
        );
    }
    
    public function testEmailInvalid() {
        $this->assertEquals(
                -10, 
                $this->object->email("whatever")
        );
    }

    /**
     * @covers ProfileUpdateController::phone
     */
    public function testPhone() {
        $this->assertEquals(
                0, 
                $this->object->phone("2310790790")
        );
    }
    
    public function testPhoneExists() {
        $this->assertEquals(
                -11,
                $this->object->phone("2321056230")
        );
    }
    
    public function testPhoneEmpty() {
        $this->assertEquals(
                -12, 
                $this->object->phone("")
        );
    }
    
    public function testPhoneInvalid() {
        $this->assertEquals(
                -13, 
                $this->object->phone("whatever")
        );
    }
    
    public function testPhoneLessThan10() {
        $this->assertEquals(
                -13, 
                $this->object->phone("2345")
        );
    }

    /**
     * @covers ProfileUpdateController::city
     */
    public function testCity() {
        $this->assertEquals(
                0, 
                $this->object->city("thessaloniki")
        );
    }
    
    public function testCityEmpty() {
        $this->assertEquals(
                -14, 
                $this->object->city("")
        );
    }

    /**
     * @covers ProfileUpdateController::address
     */
    public function testAddress() {
        $this->assertEquals(
                0, 
                $this->object->address("emporiou 10")
        );
    }
    
    public function testAddressEmpty() {
        $this->assertEquals(
                -15, 
                $this->object->address("")
        );
    }

    /**
     * @covers ProfileUpdateController::postalCode
     */
    public function testPostalCode() {
        $this->assertEquals(
                0, 
                $this->object->postalCode("57100")
        );
    }
    
    public function testPostalCodeEmpty() {
        $this->assertEquals(
                -16, 
                $this->object->postalCode("")
        );
    }

    /**
     * @covers ProfileUpdateController::latitude
     */
    public function testLatitude() {
        $this->assertEquals(
                0, 
                $this->object->latitude("40.401000")
        );
    }
    
    public function testLatitudeEmpty() {
        $this->assertEquals(
                -17, 
                $this->object->latitude("")
        );
    }

    /**
     * @covers ProfileUpdateController::longitude
     */
    public function testLongitude() {
        $this->assertEquals(
                0, 
                $this->object->longitude("40.401000")
        );
    }
    
    public function testLongitudeEmpty() {
        $this->assertEquals(
                -18, 
                $this->object->longitude("")
        );
    }

}
