<?php
    include_once "/../../../application/models/company.php";
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-12-19 at 16:53:18.
 */
class companyTest extends PHPUnit_Framework_TestCase {

    /**
     * @var company
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new company;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers company::AuthenticateUser
     * @todo   Implement testAuthenticateUser().
     */
    public function testAuthenticateUser() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers company::AddCompany
     * @todo   Implement testAddCompany().
     */
    public function testAddCompany() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers company::UpdateProfile
     * @todo   Implement testUpdateProfile().
     */
    public function testUpdateProfile() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers company::AutofillUpdateProfileForm
     * @todo   Implement testAutofillUpdateProfileForm().
     */
    public function testAutofillUpdateProfileForm() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers company::RegisterCompNameExists
     * @todo   Implement testRegisterCompNameExists().
     */
    public function testRegisterCompNameExists() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers company::RegisterEmailExists
     * @todo   Implement testRegisterEmailExists().
     */
    public function testRegisterEmailExists() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers company::RegisterPhoneExists
     * @todo   Implement testRegisterPhoneExists().
     */
    public function testRegisterPhoneExists() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers company::UpdateCompNameExists
     * @todo   Implement testUpdateCompNameExists().
     */
    public function testUpdateCompNameExists() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers company::UpdateEmailExists
     * @todo   Implement testUpdateEmailExists().
     */
    public function testUpdateEmailExists() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers company::UpdatePhoneExists
     * @todo   Implement testUpdatePhoneExists().
     */
    public function testUpdatePhoneExists() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
