<?php

include_once '/../../../application/models/offer.php';

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-12-19 at 16:43:57.
 */

class offerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var offer
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new offer;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers offer::AddOffer
     * @todo   Implement testAddOffer().
     */
    public function testAddOffer() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
